<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>OpenCg.Examples</AssemblyName>
    <RootNamespace>OpenCg.Examples</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK.Graphics" Version="4.8.2" />
    <PackageReference Include="OpenTK.Mathematics" Version="4.8.2" />
    <PackageReference Include="OpenTK.Windowing.Common" Version="4.8.2" />
    <PackageReference Include="OpenTK.Windowing.Desktop" Version="4.8.2" />
    <PackageReference Include="OpenTK.Windowing.GraphicsLibraryFramework" Version="4.8.2" />
    <PackageReference Include="Pfim" Version="0.11.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenCg\OpenCg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\Shaders\*.cg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Images\*.dds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Models\*.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\cg.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
