void main(float4 position             : POSITION,
          float3 normal               : NORMAL,
          float2 texCoord             : TEXCOORD0,
          uniform float4x4 modelViewProj,
          uniform float4x4 modelView,
          uniform float4x4 modelViewInvT,
          out float4 outPosition      : POSITION,
          out float2 outTexCoord      : TEXCOORD0,
          out float3 eyePosition      : TEXCOORD1,
          out float3 eyeNormal        : TEXCOORD2)
{
    outPosition = mul(modelViewProj, position);
    eyePosition = mul(modelView, position).xyz;
    eyeNormal = normalize(mul(modelViewInvT, float4(normal, 0.0)).xyz);
    outTexCoord = texCoord;
}
